apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site-management
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
#    namespace: test-sno-siteconfig
  project: default
  source:
    path: mgmt/configs/config-site
    repoURL: https://github.com/Sin317/telco-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
